# Handing Null Values

In [1]:
!pip install pandas

Requirement already satisfied: pandas in c:\users\yingh\venv\lib\site-packages (3.0.3)
Requirement already satisfied: numpy>=1.26.0 in c:\users\yingh\venv\lib\site-packages (from pandas) (2.4.6)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\yingh\venv\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\yingh\venv\lib\site-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in c:\users\yingh\venv\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip is available: 25.2 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [2]:
import pandas as pd

In [3]:
coffee = pd.read_csv("./warmup-data/coffee.csv")

In [4]:
coffee.head()

         Day Coffee Type  Units Sold
0     Monday    Espresso          25
1     Monday       Latte          15
2    Tuesday    Espresso          30
3    Tuesday       Latte          20
4  Wednesday    Espresso          35

In [5]:
import numpy as np
coffee["price"] = np.where(
    coffee["Coffee Type"] == "Espresso",4.99,
    5.99
)

In [6]:
coffee.head()

         Day Coffee Type  Units Sold  price
0     Monday    Espresso          25   4.99
1     Monday       Latte          15   5.99
2    Tuesday    Espresso          30   4.99
3    Tuesday       Latte          20   5.99
4  Wednesday    Espresso          35   4.99

In [7]:
coffee["revenue"] = coffee["price"] * coffee["Units Sold"]

In [8]:
coffee.head()

         Day Coffee Type  Units Sold  price  revenue
0     Monday    Espresso          25   4.99   124.75
1     Monday       Latte          15   5.99    89.85
2    Tuesday    Espresso          30   4.99   149.70
3    Tuesday       Latte          20   5.99   119.80
4  Wednesday    Espresso          35   4.99   174.65

In [9]:
#设置两个coffee的price为nan
coffee.loc[[0,1],"Units Sold"] = np.nan

## 1.查看空值

In [10]:
coffee.head()

         Day Coffee Type  Units Sold  price  revenue
0     Monday    Espresso         NaN   4.99   124.75
1     Monday       Latte         NaN   5.99    89.85
2    Tuesday    Espresso        30.0   4.99   149.70
3    Tuesday       Latte        20.0   5.99   119.80
4  Wednesday    Espresso        35.0   4.99   174.65

In [11]:
coffee.info()

<class 'pandas.DataFrame'>
RangeIndex: 14 entries, 0 to 13
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Day          14 non-null     str
 1   Coffee Type  14 non-null     str
 2   Units Sold   12 non-null     float64
 3   price        14 non-null     float64
 4   revenue      14 non-null     float64
dtypes: float64(3), str(2)
memory usage: 692.0 bytes

In [12]:
coffee.isna().sum()

Day            0
Coffee Type    0
Units Sold     2
price          0
revenue        0
dtype: int64

## 2. 给nan赋值

In [13]:
#直接赋值，注意这里也是有inpalce默认为false
coffee.fillna(10000)

          Day Coffee Type  Units Sold  price  revenue
0      Monday    Espresso     10000.0   4.99   124.75
1      Monday       Latte     10000.0   5.99    89.85
2     Tuesday    Espresso        30.0   4.99   149.70
3     Tuesday       Latte        20.0   5.99   119.80
4   Wednesday    Espresso        35.0   4.99   174.65
5   Wednesday       Latte        25.0   5.99   149.75
6    Thursday    Espresso        40.0   4.99   199.60
7    Thursday       Latte        30.0   5.99   179.70
8      Friday    Espresso        45.0   4.99   224.55
9      Friday       Latte        35.0   5.99   209.65
10   Saturday    Espresso        45.0   4.99   224.55
11   Saturday       Latte        35.0   5.99   209.65
12     Sunday    Espresso        45.0   4.99   224.55
13     Sunday       Latte        35.0   5.99   209.65

In [14]:
#赋予nan均值
coffee.fillna(coffee["Units Sold"].mean())

          Day Coffee Type  Units Sold  price  revenue
0      Monday    Espresso        35.0   4.99   124.75
1      Monday       Latte        35.0   5.99    89.85
2     Tuesday    Espresso        30.0   4.99   149.70
3     Tuesday       Latte        20.0   5.99   119.80
4   Wednesday    Espresso        35.0   4.99   174.65
5   Wednesday       Latte        25.0   5.99   149.75
6    Thursday    Espresso        40.0   4.99   199.60
7    Thursday       Latte        30.0   5.99   179.70
8      Friday    Espresso        45.0   4.99   224.55
9      Friday       Latte        35.0   5.99   209.65
10   Saturday    Espresso        45.0   4.99   224.55
11   Saturday       Latte        35.0   5.99   209.65
12     Sunday    Espresso        45.0   4.99   224.55
13     Sunday       Latte        35.0   5.99   209.65

In [15]:
#赋予nan插值,首尾连续的话没法赋予
coffee.fillna(coffee["Units Sold"].interpolate())

          Day Coffee Type  Units Sold  price  revenue
0      Monday    Espresso         NaN   4.99   124.75
1      Monday       Latte         NaN   5.99    89.85
2     Tuesday    Espresso        30.0   4.99   149.70
3     Tuesday       Latte        20.0   5.99   119.80
4   Wednesday    Espresso        35.0   4.99   174.65
5   Wednesday       Latte        25.0   5.99   149.75
6    Thursday    Espresso        40.0   4.99   199.60
7    Thursday       Latte        30.0   5.99   179.70
8      Friday    Espresso        45.0   4.99   224.55
9      Friday       Latte        35.0   5.99   209.65
10   Saturday    Espresso        45.0   4.99   224.55
11   Saturday       Latte        35.0   5.99   209.65
12     Sunday    Espresso        45.0   4.99   224.55
13     Sunday       Latte        35.0   5.99   209.65

In [16]:
coffee.fillna(15,inplace = True)

          Day Coffee Type  Units Sold  price  revenue
0      Monday    Espresso        15.0   4.99   124.75
1      Monday       Latte        15.0   5.99    89.85
2     Tuesday    Espresso        30.0   4.99   149.70
3     Tuesday       Latte        20.0   5.99   119.80
4   Wednesday    Espresso        35.0   4.99   174.65
5   Wednesday       Latte        25.0   5.99   149.75
6    Thursday    Espresso        40.0   4.99   199.60
7    Thursday       Latte        30.0   5.99   179.70
8      Friday    Espresso        45.0   4.99   224.55
9      Friday       Latte        35.0   5.99   209.65
10   Saturday    Espresso        45.0   4.99   224.55
11   Saturday       Latte        35.0   5.99   209.65
12     Sunday    Espresso        45.0   4.99   224.55
13     Sunday       Latte        35.0   5.99   209.65

In [17]:
coffee.loc[[2,3],"Units Sold"] = np.nan

In [18]:
coffee.head()

         Day Coffee Type  Units Sold  price  revenue
0     Monday    Espresso        15.0   4.99   124.75
1     Monday       Latte        15.0   5.99    89.85
2    Tuesday    Espresso         NaN   4.99   149.70
3    Tuesday       Latte         NaN   5.99   119.80
4  Wednesday    Espresso        35.0   4.99   174.65

In [19]:
coffee["Units Sold"].interpolate()

0     15.000000
1     15.000000
2     21.666667
3     28.333333
4     35.000000
5     25.000000
6     40.000000
7     30.000000
8     45.000000
9     35.000000
10    45.000000
11    35.000000
12    45.000000
13    35.000000
Name: Units Sold, dtype: float64

In [20]:
coffee["Units Sold"] = coffee["Units Sold"].interpolate()

In [21]:
coffee.head()

         Day Coffee Type  Units Sold  price  revenue
0     Monday    Espresso   15.000000   4.99   124.75
1     Monday       Latte   15.000000   5.99    89.85
2    Tuesday    Espresso   21.666667   4.99   149.70
3    Tuesday       Latte   28.333333   5.99   119.80
4  Wednesday    Espresso   35.000000   4.99   174.65

In [22]:
coffee.loc[[1,2,3],["Units Sold"]] = np.nan

In [23]:
coffee.loc[[1,2],"price"] = np.nan

In [24]:
coffee

          Day Coffee Type  Units Sold  price  revenue
0      Monday    Espresso        15.0   4.99   124.75
1      Monday       Latte         NaN    NaN    89.85
2     Tuesday    Espresso         NaN    NaN   149.70
3     Tuesday       Latte         NaN   5.99   119.80
4   Wednesday    Espresso        35.0   4.99   174.65
5   Wednesday       Latte        25.0   5.99   149.75
6    Thursday    Espresso        40.0   4.99   199.60
7    Thursday       Latte        30.0   5.99   179.70
8      Friday    Espresso        45.0   4.99   224.55
9      Friday       Latte        35.0   5.99   209.65
10   Saturday    Espresso        45.0   4.99   224.55
11   Saturday       Latte        35.0   5.99   209.65
12     Sunday    Espresso        45.0   4.99   224.55
13     Sunday       Latte        35.0   5.99   209.65

# 3.Drop nan 删掉空值

In [25]:
coffee.dropna()

          Day Coffee Type  Units Sold  price  revenue
0      Monday    Espresso        15.0   4.99   124.75
4   Wednesday    Espresso        35.0   4.99   174.65
5   Wednesday       Latte        25.0   5.99   149.75
6    Thursday    Espresso        40.0   4.99   199.60
7    Thursday       Latte        30.0   5.99   179.70
8      Friday    Espresso        45.0   4.99   224.55
9      Friday       Latte        35.0   5.99   209.65
10   Saturday    Espresso        45.0   4.99   224.55
11   Saturday       Latte        35.0   5.99   209.65
12     Sunday    Espresso        45.0   4.99   224.55
13     Sunday       Latte        35.0   5.99   209.65

In [26]:
#只去掉subet一列的nan
coffee.dropna(subset = ["price"])

          Day Coffee Type  Units Sold  price  revenue
0      Monday    Espresso        15.0   4.99   124.75
3     Tuesday       Latte         NaN   5.99   119.80
4   Wednesday    Espresso        35.0   4.99   174.65
5   Wednesday       Latte        25.0   5.99   149.75
6    Thursday    Espresso        40.0   4.99   199.60
7    Thursday       Latte        30.0   5.99   179.70
8      Friday    Espresso        45.0   4.99   224.55
9      Friday       Latte        35.0   5.99   209.65
10   Saturday    Espresso        45.0   4.99   224.55
11   Saturday       Latte        35.0   5.99   209.65
12     Sunday    Espresso        45.0   4.99   224.55
13     Sunday       Latte        35.0   5.99   209.65

In [27]:
#drop函数也需要写inplace = True 或是赋值给原本的变量
#获取为nan的行
coffee[coffee["Units Sold"].isna()]

       Day Coffee Type  Units Sold  price  revenue
1   Monday       Latte         NaN    NaN    89.85
2  Tuesday    Espresso         NaN    NaN   149.70
3  Tuesday       Latte         NaN   5.99   119.80

In [28]:
#获取不为nan的行
coffee[coffee["Units Sold"].notna()]

          Day Coffee Type  Units Sold  price  revenue
0      Monday    Espresso        15.0   4.99   124.75
4   Wednesday    Espresso        35.0   4.99   174.65
5   Wednesday       Latte        25.0   5.99   149.75
6    Thursday    Espresso        40.0   4.99   199.60
7    Thursday       Latte        30.0   5.99   179.70
8      Friday    Espresso        45.0   4.99   224.55
9      Friday       Latte        35.0   5.99   209.65
10   Saturday    Espresso        45.0   4.99   224.55
11   Saturday       Latte        35.0   5.99   209.65
12     Sunday    Espresso        45.0   4.99   224.55
13     Sunday       Latte        35.0   5.99   209.65

In [29]:
coffee.to_csv("./warmup-data/coffee_updated.csv",index = False)