聚合就是分组嘛

# 1.groupby分组

In [2]:
import pandas as pd

bios = pd.read_csv("./data/bios.csv")

In [3]:
bios.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25

In [4]:
bios["born_region"].value_counts()

born_region
England            4824
Ontario            1710
California         1634
Budapest           1447
New South Wales    1120
                   ...
Kalasin               1
Iğdır                 1
Ağstafa               1
Sihanoukville         1
Vĩnh Long             1
Name: count, Length: 2554, dtype: int64

In [5]:
bios[bios["born_country"] == "USA"]["born_region"].value_counts()

born_region
California              1634
New York                 990
Illinois                 585
Pennsylvania             530
Massachusetts            530
New Jersey               381
Texas                    368
Minnesota                365
Ohio                     328
Michigan                 319
Washington               240
Florida                  235
Wisconsin                209
Colorado                 207
Connecticut              156
Indiana                  150
Oregon                   132
Georgia                  129
Virginia                 121
Maryland                 117
District of Columbia     107
Iowa                     102
Hawaiʻi                   95
Kansas                    94
Oklahoma                  93
Louisiana                 92
Utah                      91
Missouri                  91
North Carolina            86
Arizona                   83
New Hampshire             83
Vermont                   68
Mississippi               66
Alabama                   64
Tennessee                 62
Kentucky                  62
Nebraska                  60
Rhode Island              56
Montana                   55
Maine                     50
South Carolina            50
Alaska                    45
Arkansas                  42
Idaho                     41
New Mexico                38
Nevada                    36
South Dakota              27
West Virginia             24
Delaware                  22
North Dakota              16
Wyoming                   14
Name: count, dtype: int64

In [6]:
bios[bios["born_country"] == "USA"]["born_region"].value_counts().tail(20)

born_region
Vermont           68
Mississippi       66
Alabama           64
Tennessee         62
Kentucky          62
Nebraska          60
Rhode Island      56
Montana           55
Maine             50
South Carolina    50
Alaska            45
Arkansas          42
Idaho             41
New Mexico        38
Nevada            36
South Dakota      27
West Virginia     24
Delaware          22
North Dakota      16
Wyoming           14
Name: count, dtype: int64

In [8]:
coffee = pd.read_csv("./warmup-data/coffee.csv")

In [10]:
coffee.head()

         Day Coffee Type  Units Sold
0     Monday    Espresso          25
1     Monday       Latte          15
2    Tuesday    Espresso          30
3    Tuesday       Latte          20
4  Wednesday    Espresso          35

In [13]:
coffee.groupby("Coffee Type")["Units Sold"].sum()

Coffee Type
Espresso    265
Latte       195
Name: Units Sold, dtype: int64

In [14]:
coffee.groupby("Coffee Type")["Units Sold"].mean()

Coffee Type
Espresso    37.857143
Latte       27.857143
Name: Units Sold, dtype: float64

In [15]:
coffee["Price"] = coffee["Coffee Type"].apply(lambda x: 4.99 if x == "Espresso" else 5.99)

In [ ]:
#groupby算出中间过程，agg传入字典，指定不同聚合函数的结果是求啥，平均还是求和还是啥
coffee.groupby("Coffee Type").agg({
    "Units Sold":"sum",
    "Price":"mean"})

             Units Sold  Price
Coffee Type
Espresso            265   4.99
Latte               195   5.99

In [17]:
coffee.groupby(["Coffee Type","Day"]).agg({
    "Units Sold":"sum",
    "Price":"mean"})

                       Units Sold  Price
Coffee Type Day
Espresso    Friday             45   4.99
            Monday             25   4.99
            Saturday           45   4.99
            Sunday             45   4.99
            Thursday           40   4.99
            Tuesday            30   4.99
            Wednesday          35   4.99
Latte       Friday             35   5.99
            Monday             15   5.99
            Saturday           35   5.99
            Sunday             35   5.99
            Thursday           30   5.99
            Tuesday            20   5.99
            Wednesday          25   5.99

# 2.pivot table枢纽，透视表

In [18]:
coffee["revenue"] = coffee["Units Sold"] * coffee["Price"]

In [19]:
pivot = coffee.pivot(columns = "Coffee Type",index = "Day",values = "revenue")

In [21]:
coffee

          Day Coffee Type  Units Sold  Price  revenue
0      Monday    Espresso          25   4.99   124.75
1      Monday       Latte          15   5.99    89.85
2     Tuesday    Espresso          30   4.99   149.70
3     Tuesday       Latte          20   5.99   119.80
4   Wednesday    Espresso          35   4.99   174.65
5   Wednesday       Latte          25   5.99   149.75
6    Thursday    Espresso          40   4.99   199.60
7    Thursday       Latte          30   5.99   179.70
8      Friday    Espresso          45   4.99   224.55
9      Friday       Latte          35   5.99   209.65
10   Saturday    Espresso          45   4.99   224.55
11   Saturday       Latte          35   5.99   209.65
12     Sunday    Espresso          45   4.99   224.55
13     Sunday       Latte          35   5.99   209.65

In [20]:
pivot

Coffee Type  Espresso   Latte
Day
Friday         224.55  209.65
Monday         124.75   89.85
Saturday       224.55  209.65
Sunday         224.55  209.65
Thursday       199.60  179.70
Tuesday        149.70  119.80
Wednesday      174.65  149.75

In [ ]:
#有新的方式访问
#转成行列+表格里的值的写法
pivot.loc["Monday","Latte"]

np.float64(89.85000000000001)

In [ ]:
#列加和不包括index
pivot.sum()

Coffee Type
Espresso    1322.35
Latte       1168.05
dtype: float64

In [ ]:
#行加和
pivot.sum(axis = 1)

Day
Friday       434.2
Monday       214.6
Saturday     434.2
Sunday       434.2
Thursday     379.3
Tuesday      269.5
Wednesday    324.4
dtype: float64

In [27]:
bios.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25

In [28]:
bios["born_date"] = pd.to_datetime(bios["born_date"])

In [ ]:
#dt.year访问datetime类型的年份
bios.groupby(bios["born_date"].dt.year)["name"].count()

born_date
1828.0      1
1831.0      2
1833.0      1
1836.0      1
1837.0      1
         ...
2005.0    163
2006.0     17
2007.0      3
2008.0      3
2009.0      1
Name: name, Length: 177, dtype: int64

In [ ]:
#先给一个序列index然后递减排序
bios.groupby(bios["born_date"].dt.year)["name"].count().reset_index().sort_values("name",ascending = False)

     born_date  name
139     1972.0  2231
152     1985.0  2227
140     1973.0  2216
138     1971.0  2205
137     1970.0  2174
..         ...   ...
4       1837.0     1
2       1833.0     1
6       1839.0     1
12      1845.0     1
176     2009.0     1

[177 rows x 2 columns]

In [32]:
bios["born_year"] = bios["born_date"].dt.year
bios["born_month"] = bios["born_date"].dt.month

bios.groupby(["born_year", "born_month"])["name"].count().reset_index().sort_values("name", ascending=False)

      born_year  born_month  name
1437     1970.0         1.0   239
1461     1972.0         1.0   229
1497     1975.0         1.0   227
1629     1986.0         1.0   227
1617     1985.0         1.0   225
...         ...         ...   ...
1877     2006.0        12.0     1
1871     2006.0         3.0     1
20       1846.0         7.0     1
21       1846.0         8.0     1
22       1846.0         9.0     1

[1885 rows x 3 columns]

In [33]:
#也可以写成
bios.groupby([bios["born_year"], bios["born_month"]])["name"].count().reset_index().sort_values("name", ascending=False)

      born_year  born_month  name
1437     1970.0         1.0   239
1461     1972.0         1.0   229
1497     1975.0         1.0   227
1629     1986.0         1.0   227
1617     1985.0         1.0   225
...         ...         ...   ...
1877     2006.0        12.0     1
1871     2006.0         3.0     1
20       1846.0         7.0     1
21       1846.0         8.0     1
22       1846.0         9.0     1

[1885 rows x 3 columns]