In [ ]:
# .shift() .rank() .rolling() .cumsum()

# 1.shift移动

In [2]:
import pandas as pd
coffee = pd.read_csv("./warmup-data/coffee_updated.csv")

In [6]:
#因为有两行所以移2下，然后可以比较上周的收入和这周的收入
coffee["yesterday_revenue"] = coffee["revenue"].shift(2)

In [7]:
coffee.head()

         Day Coffee Type  Units Sold  price  revenue  yesterday_revenue
0     Monday    Espresso        15.0   4.99   124.75                NaN
1     Monday       Latte         NaN    NaN    89.85                NaN
2    Tuesday    Espresso         NaN    NaN   149.70             124.75
3    Tuesday       Latte         NaN   5.99   119.80              89.85
4  Wednesday    Espresso        35.0   4.99   174.65             149.70

# 2.rank排序

In [3]:
bios = pd.read_csv("./data/bios.csv")

In [4]:
bios.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25

In [5]:
bios["height_rank"] = bios["height_cm"].rank()

In [6]:
bios.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,height_rank
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,NaN
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN,79054.5
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17,79054.5
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20,22677.0
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25,NaN

In [9]:
bios.sort_values(["height_rank"],ascending = False)

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,height_rank
89070,89782,Yao Ming,1980-09-12,Xuhui District,Shanghai,CHN,People's Republic of China,226.0,141.0,NaN,106651.0
6978,7013,Arvydas Sabonis,1964-12-19,Kaunas,Kaunas,LTU,Lithuania Soviet Union,223.0,122.0,NaN,106649.5
5781,5804,Tommy Burleson,1952-02-24,Crossnore,North Carolina,USA,United States,223.0,102.0,NaN,106649.5
89075,89787,Roberto Dueñas,1975-11-01,Madrid,Madrid,ESP,Spain,221.0,137.0,NaN,106647.0
120266,122147,Zhang Zhaoxu,1987-11-18,Binzhou,Shandong,CHN,People's Republic of China,221.0,110.0,NaN,106647.0
...,...,...,...,...,...,...,...,...,...,...,...
145490,149217,Sin Ye-Chan,1995-06-13,NaN,NaN,NaN,Republic of Korea,NaN,NaN,NaN,NaN
145491,149218,Matthew Wepke,1989-12-05,NaN,NaN,NaN,Jamaica,NaN,NaN,NaN,NaN
145492,149219,Carlos García-Ordóñez,1927-04-24,La Habana (Havana),Ciudad de La Habana,CUB,Cuba,NaN,NaN,2019-11-24,NaN
145493,149220,Landysh Falyakhova,1998-08-31,Dva Polya Artash,Respublika Tatarstan,RUS,ROC,NaN,NaN,NaN,NaN
145499,149814,Bill Phillips,1913-07-15,Dulwich Hill,New South Wales,AUS,Australia,NaN,NaN,2003-10-20,NaN

# 3.cumsum累加/cumulative

In [10]:
coffee.head()

         Day Coffee Type  Units Sold  price  revenue
0     Monday    Espresso        15.0   4.99   124.75
1     Monday       Latte         NaN    NaN    89.85
2    Tuesday    Espresso         NaN    NaN   149.70
3    Tuesday       Latte         NaN   5.99   119.80
4  Wednesday    Espresso        35.0   4.99   174.65

In [11]:
coffee["cumsum_revenue"] = coffee["revenue"].cumsum()

In [12]:
coffee.head()

         Day Coffee Type  Units Sold  price  revenue  cumsum_revenue
0     Monday    Espresso        15.0   4.99   124.75          124.75
1     Monday       Latte         NaN    NaN    89.85          214.60
2    Tuesday    Espresso         NaN    NaN   149.70          364.30
3    Tuesday       Latte         NaN   5.99   119.80          484.10
4  Wednesday    Espresso        35.0   4.99   174.65          658.75

# 3. rolling滚动窗口

In [17]:
latte = coffee[coffee["Coffee Type"] == "Latte"].copy()
latte

          Day Coffee Type  Units Sold  price  revenue  cumsum_revenue
1      Monday       Latte         NaN    NaN    89.85           214.6
3     Tuesday       Latte         NaN   5.99   119.80           484.1
5   Wednesday       Latte        25.0   5.99   149.75           808.5
7    Thursday       Latte        30.0   5.99   179.70          1187.8
9      Friday       Latte        35.0   5.99   209.65          1622.0
11   Saturday       Latte        35.0   5.99   209.65          2056.2
13     Sunday       Latte        35.0   5.99   209.65          2490.4

In [19]:
latte["3day Units Sold"] = latte["Units Sold"].rolling(3).sum()

In [20]:
latte

,Day,Coffee Type,Units Sold,price,revenue,cumsum_revenue,3day Units Sold
1,Monday,Latte,NaN,NaN,89.85,214.6,NaN
3,Tuesday,Latte,NaN,5.99,119.80,484.1,NaN
5,Wednesday,Latte,25.0,5.99,149.75,808.5,NaN
7,Thursday,Latte,30.0,5.99,179.70,1187.8,NaN
9,Friday,Latte,35.0,5.99,209.65,1622.0,90.0
11,Saturday,Latte,35.0,5.99,209.65,2056.2,100.0
13,Sunday,Latte,35.0,5.99,209.65,2490.4,105.0