# 1. Introduction to DataFrame

In [2]:
pip install pandas

Requirement already satisfied: pandas in .\.venv\lib\site-packages (3.0.3)
Requirement already satisfied: numpy>=1.26.0 in .\.venv\lib\site-packages (from pandas) (2.4.6)
Requirement already satisfied: python-dateutil>=2.8.2 in .\.venv\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in .\.venv\lib\site-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in .\.venv\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.2 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [1]:
import pandas as pd

#columns 指定列名,是元素之外的额外指定的，注意在二维方括号外面但是在括号里面
df = pd.DataFrame([[1,2,3],[4,5,6],[7,8,9]],columns = ["A","B","C"])

## 1.1 展示 show

In [ ]:
#显示前五行
df.head()
#最左边一列的0，1，2，被叫做索引index

   A  B  C
0  1  2  3
1  4  5  6
2  7  8  9

In [ ]:
#head里可以指定看前i行
df.head(1)

   A  B  C
0  1  2  3

In [10]:
df.head(2)

   A  B  C
0  1  2  3
1  4  5  6

In [11]:
df.tail()

   A  B  C
0  1  2  3
1  4  5  6
2  7  8  9

In [12]:
df.tail(2)

   A  B  C
1  4  5  6
2  7  8  9

In [13]:
df.columns

Index(['A', 'B', 'C'], dtype='str')

## 1.2 Index Show

In [ ]:
#pandas把index设计为一种数据类型，rangeindex是index的一种
df.index

RangeIndex(start=0, stop=3, step=1)

In [ ]:
#tolist()
df.index.tolist()

[0, 1, 2]

In [20]:
df.index = ["x","y","z"]
df.index

Index(['x', 'y', 'z'], dtype='str')

## 1.3 More Information

In [21]:
df.info()

<class 'pandas.DataFrame'>
Index: 3 entries, x to z
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       3 non-null      int64
 1   B       3 non-null      int64
 2   C       3 non-null      int64
dtypes: int64(3)
memory usage: 96.0+ bytes

In [ ]:
#25%和75%代表第一四分位和第三四分位，first quartile和third quartile
#平均数，然后（第一个数+平均数）/2  
df.describe()

         A    B    C
count  3.0  3.0  3.0
mean   4.0  5.0  6.0
std    3.0  3.0  3.0
min    1.0  2.0  3.0
25%    2.5  3.5  4.5
50%    4.0  5.0  6.0
75%    5.5  6.5  7.5
max    7.0  8.0  9.0

In [ ]:
#每一列唯一值的数量
df.nunique()

A    3
B    3
C    3
dtype: int64

In [24]:
df["A"].nunique()

3

In [25]:
df

   A  B  C
x  1  2  3
y  4  5  6
z  7  8  9

In [26]:
df.shape

(3, 3)

In [27]:
df.size

9

In [31]:
df["zz"] = [10,11,12]
df

   A  B  C  zz
x  1  2  3  10
y  4  5  6  11
z  7  8  9  12

In [ ]:
#为了避免行列重名，加了一个axis,axis = 1代表列，axis = 0代表行;
# 此外，axis在对行或是对列操作时，默认是axis = 0
df = df.drop("zz",axis = 1)
#或是df.drop("zz",axis = 1,inplace = True)
df

   A  B  C
x  1  2  3
y  4  5  6
z  7  8  9

# 2. Loading in DataFrames from Files

## 2.1 读取 CSV

In [10]:
coffee = pd.read_csv('./warmup-data/coffee.csv')
#或是coffee = pd.read_csv("https://raw.githubusercontent.com/KeithGalli/complete-pandas-tutorial/refs/heads/master/warmup-data/coffee.csv")
#这是github点开csv文件之后，点右上角的raw，然后复制链接，效果是一样的

In [35]:
coffee.head()

         Day Coffee Type  Units Sold
0     Monday    Espresso          25
1     Monday       Latte          15
2    Tuesday    Espresso          30
3    Tuesday       Latte          20
4  Wednesday    Espresso          35

## 2.2 读取 Parquet

In [ ]:
#这个库里包含了对parquet等文件的IO操作的支持，只有pandas不能读取parquet文件
pip install pyarrow

Collecting pyarrow
  Downloading pyarrow-24.0.0-cp313-cp313-win_amd64.whl.metadata (3.0 kB)
Downloading pyarrow-24.0.0-cp313-cp313-win_amd64.whl (27.3 MB)
   ---------------------------------------- 0.0/27.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/27.3 MB ? eta -:--:--
   ---------------------------------------- 0.3/27.3 MB ? eta -:--:--
    --------------------------------------- 0.5/27.3 MB 1.1 MB/s eta 0:00:25
   - -------------------------------------- 0.8/27.3 MB 1.1 MB/s eta 0:00:24
   - -------------------------------------- 1.0/27.3 MB 1.2 MB/s eta 0:00:23
   - -------------------------------------- 1.3/27.3 MB 1.2 MB/s eta 0:00:23
   -- ------------------------------------- 1.6/27.3 MB 1.2 MB/s eta 0:00:23
   -- ------------------------------------- 1.8/27.3 MB 1.2 MB/s eta 0:00:22
   --- ------------------------------------ 2.1/27.3 MB 1.2 MB/s eta 0:00:22
   --- ------------------------------------ 2.4/27.3 MB 1.2 MB/s eta 0:00:22
   --- ------------------------------------ 2.6/27.3 MB 1.2 MB/s eta 0:00:22
   ---- ----------------------------------- 2.9/27.3 MB 1.2 MB/s eta 0:00:21
   ---- ----------------------------------- 3.1/27.3 MB 1.2 MB/s eta 0:00:21
   ---- ----------------------------------- 3.1/27.3 MB 1.2 MB/s eta 0:00:21
   ---- ----------------------------------- 3.4/27.3 MB 1.2 MB/s eta 0:00:21
   ----- ---------------------------------- 3.7/27.3 MB 1.2 MB/s eta 0:00:21
   ----- ---------------------------------- 3.9/27.3 MB 1.2 MB/s eta 0:00:21
   ------ --------------------------------- 4.2/27.3 MB 1.2 MB/s eta 0:00:20
   ------ --------------------------------- 4.5/27.3 MB 1.2 MB/s eta 0:00:20
   ------ --------------------------------- 4.7/27.3 MB 1.2 MB/s eta 0:00:20
   ------- -------------------------------- 5.0/27.3 MB 1.2 MB/s eta 0:00:20
   ------- -------------------------------- 5.2/27.3 MB 1.2 MB/s eta 0:00:19
   -------- ------------------------------- 5.5/27.3 MB 1.2 MB/s eta 0:00:19
   -------- ------------------------------- 5.8/27.3 MB 1.2 MB/s eta 0:00:19
   -------- ------------------------------- 6.0/27.3 MB 1.2 MB/s eta 0:00:19
   -------- ------------------------------- 6.0/27.3 MB 1.2 MB/s eta 0:00:19
   --------- ------------------------------ 6.3/27.3 MB 1.2 MB/s eta 0:00:19
   --------- ------------------------------ 6.6/27.3 MB 1.2 MB/s eta 0:00:18
   --------- ------------------------------ 6.8/27.3 MB 1.2 MB/s eta 0:00:18
   ---------- ----------------------------- 7.1/27.3 MB 1.2 MB/s eta 0:00:18
   ---------- ----------------------------- 7.3/27.3 MB 1.2 MB/s eta 0:00:18
   ----------- ---------------------------- 7.6/27.3 MB 1.2 MB/s eta 0:00:18
   ----------- ---------------------------- 7.9/27.3 MB 1.2 MB/s eta 0:00:17
   ----------- ---------------------------- 8.1/27.3 MB 1.2 MB/s eta 0:00:17
   ------------ --------------------------- 8.4/27.3 MB 1.2 MB/s eta 0:00:17
   ------------ --------------------------- 8.4/27.3 MB 1.2 MB/s eta 0:00:17
   ------------ --------------------------- 8.7/27.3 MB 1.1 MB/s eta 0:00:17
   ------------- -------------------------- 8.9/27.3 MB 1.1 MB/s eta 0:00:16
   ------------- -------------------------- 9.2/27.3 MB 1.1 MB/s eta 0:00:16
   ------------- -------------------------- 9.4/27.3 MB 1.1 MB/s eta 0:00:16
   ------------- -------------------------- 9.4/27.3 MB 1.1 MB/s eta 0:00:16
   -------------- ------------------------- 9.7/27.3 MB 1.1 MB/s eta 0:00:16
   -------------- ------------------------- 10.0/27.3 MB 1.1 MB/s eta 0:00:16
   -------------- ------------------------- 10.2/27.3 MB 1.1 MB/s eta 0:00:16
   --------------- ------------------------ 10.5/27.3 MB 1.1 MB/s eta 0:00:15
   --------------- ------------------------ 10.7/27.3 MB 1.1 MB/s eta 0:00:15
   ---------------- ----------------------- 11.0/27.3 MB 1.1 MB/s eta 0:00:15
   ---------------- ----------------------- 11.3/27.3 MB 1.1 MB/s eta 0:00:15
   ---------------- ----------------------- 11.5/27.3 MB 1.1 MB/s eta 0:00:14
   ----------------- ---------------------- 11.8/27.3 MB 1.1 MB/s eta 0:00:14
   ----------------- ---------------------- 12.1/27.3 MB 1.1 MB/s eta 0:00:14
   ------------------ --------------------- 12.3/27.3 MB 1.1 MB/s eta 0:00:14
   ------------------ --------------------- 12.3/27.3 MB 1.1 MB/s eta 0:00:14
   ------------------ --------------------- 12.6/27.3 MB 1.1 MB/s eta 0:00:13
   ------------------ --------------------- 12.8/27.3 MB 1.1 MB/s eta 0:00:13
   ------------------- -------------------- 13.1/27.3 MB 1.1 MB/s eta 0:00:13
   ------------------- -------------------- 13.4/27.3 MB 1.1 MB/s eta 0:00:13
   ------------------- -------------------- 13.6/27.3 MB 1.1 MB/s eta 0:00:13
   -------------------- ------------------- 13.9/27.3 MB 1.1 MB/s eta 0:00:12
   -------------------- ------------------- 14.2/27.3 MB 1.1 MB/s eta 0:00:12
   --------------------- ------------------ 14.4/27.3 MB 1.1 MB/s eta 0:00:12
   --------------------- ------------------ 14.7/27.3 MB 1.1 MB/s eta 0:00:12
   --------------------- ------------------ 14.9/27.3 MB 1.1 MB/s eta 0:00:11
   ---------------------- ----------------- 15.2/27.3 MB 1.1 MB/s eta 0:00:11
   ---------------------- ----------------- 15.5/27.3 MB 1.1 MB/s eta 0:00:11
   ---------------------- ----------------- 15.5/27.3 MB 1.1 MB/s eta 0:00:11
   ----------------------- ---------------- 15.7/27.3 MB 1.1 MB/s eta 0:00:11
   ----------------------- ---------------- 16.0/27.3 MB 1.1 MB/s eta 0:00:10
   ----------------------- ---------------- 16.3/27.3 MB 1.1 MB/s eta 0:00:10
   ------------------------ --------------- 16.5/27.3 MB 1.1 MB/s eta 0:00:10
   ------------------------ --------------- 16.8/27.3 MB 1.1 MB/s eta 0:00:10
   ------------------------ --------------- 17.0/27.3 MB 1.1 MB/s eta 0:00:10
   ------------------------- -------------- 17.3/27.3 MB 1.1 MB/s eta 0:00:09
   ------------------------- -------------- 17.6/27.3 MB 1.1 MB/s eta 0:00:09
   -------------------------- ------------- 17.8/27.3 MB 1.1 MB/s eta 0:00:09
   -------------------------- ------------- 17.8/27.3 MB 1.1 MB/s eta 0:00:09
   -------------------------- ------------- 18.1/27.3 MB 1.1 MB/s eta 0:00:09
   -------------------------- ------------- 18.4/27.3 MB 1.1 MB/s eta 0:00:08
   --------------------------- ------------ 18.6/27.3 MB 1.1 MB/s eta 0:00:08
   --------------------------- ------------ 18.9/27.3 MB 1.1 MB/s eta 0:00:08
   ---------------------------- ----------- 19.1/27.3 MB 1.1 MB/s eta 0:00:08
   ---------------------------- ----------- 19.4/27.3 MB 1.1 MB/s eta 0:00:07
   ---------------------------- ----------- 19.7/27.3 MB 1.1 MB/s eta 0:00:07
   ----------------------------- ---------- 19.9/27.3 MB 1.1 MB/s eta 0:00:07
   ----------------------------- ---------- 20.2/27.3 MB 1.1 MB/s eta 0:00:07
   ----------------------------- ---------- 20.4/27.3 MB 1.1 MB/s eta 0:00:06
   ------------------------------ --------- 20.7/27.3 MB 1.1 MB/s eta 0:00:06
   ------------------------------ --------- 21.0/27.3 MB 1.1 MB/s eta 0:00:06
   ------------------------------- -------- 21.2/27.3 MB 1.1 MB/s eta 0:00:06
   ------------------------------- -------- 21.2/27.3 MB 1.1 MB/s eta 0:00:06
   ------------------------------- -------- 21.5/27.3 MB 1.1 MB/s eta 0:00:06
   ------------------------------- -------- 21.8/27.3 MB 1.1 MB/s eta 0:00:05
   -------------------------------- ------- 22.0/27.3 MB 1.1 MB/s eta 0:00:05
   -------------------------------- ------- 22.3/27.3 MB 1.1 MB/s eta 0:00:05
   --------------------------------- ------ 22.5/27.3 MB 1.1 MB/s eta 0:00:05
   --------------------------------- ------ 22.8/27.3 MB 1.1 MB/s eta 0:00:04
   --------------------------------- ------ 23.1/27.3 MB 1.1 MB/s eta 0:00:04
   ---------------------------------- ----- 23.3/27.3 MB 1.1 MB/s eta 0:00:04
   ---------------------------------- ----- 23.6/27.3 MB 1.1 MB/s eta 0:00:04
   ---------------------------------- ----- 23.9/27.3 MB 1.1 MB/s eta 0:00:03
   ----------------------------------- ---- 24.1/27.3 MB 1.1 MB/s eta 0:00:03
   ----------------------------------- ---- 24.4/27.3 MB 1.1 MB/s eta 0:00:03
   ----------------------------------- ---- 24.4/27.3 MB 1.1 MB/s eta 0:00:03
   ------------------------------------ --- 24.6/27.3 MB 1.1 MB/s eta 0:00:03
   ------------------------------------ --- 24.9/27.3 MB 1.1 MB/s eta 0:00:03
   ------------------------------------ --- 25.2/27.3 MB 1.1 MB/s eta 0:00:02
   ------------------------------------- -- 25.4/27.3 MB 1.1 MB/s eta 0:00:02
   ------------------------------------- -- 25.7/27.3 MB 1.1 MB/s eta 0:00:02
   -------------------------------------- - 26.0/27.3 MB 1.1 MB/s eta 0:00:02
   -------------------------------------- - 26.2/27.3 MB 1.1 MB/s eta 0:00:01
   -------------------------------------- - 26.5/27.3 MB 1.1 MB/s eta 0:00:01
   ---------------------------------------  26.7/27.3 MB 1.1 MB/s eta 0:00:01
   ---------------------------------------  27.0/27.3 MB 1.1 MB/s eta 0:00:01
   ---------------------------------------  27.3/27.3 MB 1.1 MB/s eta 0:00:01
   ---------------------------------------- 27.3/27.3 MB 1.1 MB/s  0:00:23
Installing collected packages: pyarrow
Successfully installed pyarrow-24.0.0
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.2 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [11]:
results = pd.read_parquet("./data/results.parquet")

In [4]:
results.head()

,year,type,discipline,event,as,athlete_id,noc,team,place,tied,medal
0,1912.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,17.0,True,NaN
1,1912.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jean Montariol,NaN,False,NaN
2,1920.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,32.0,True,NaN
3,1920.0,Summer,Tennis,"Doubles, Mixed (Olympic)",Jean-François Blanchy,1,FRA,Jeanne Vaussard,8.0,True,NaN
4,1920.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jacques Brugnon,4.0,False,NaN

## 2.3 读取 Excel

In [7]:
pip install openpyxl

Collecting openpyxl
  Using cached openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Collecting et-xmlfile (from openpyxl)
  Using cached et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Using cached openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
Using cached et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Installing collected packages: et-xmlfile, openpyxl

   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   ---------------------------------------- 2/2 [openpyxl]

Successfully installed et-xmlfile-2.0.0 openpyxl-3.1.5
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.2 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [2]:
olympics_data = pd.read_excel("./data/olympics-data.xlsx")

In [3]:
olympics_data.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25

In [ ]:
#excel文件里有多个sheet（就是下面的那个可以取名增加的），默认是第一个sheet，如果想要指定sheet，可以用sheet_name参数
olympics_data1 = pd.read_excel("./data/olympics-data.xlsx",sheet_name = "results")

In [5]:
olympics_data1.head()

,year,type,discipline,event,as,athlete_id,noc,team,place,tied,medal
0,1912.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,17.0,True,NaN
1,1912.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jean Montariol,NaN,False,NaN
2,1920.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,32.0,True,NaN
3,1920.0,Summer,Tennis,"Doubles, Mixed (Olympic)",Jean-François Blanchy,1,FRA,Jeanne Vaussard,8.0,True,NaN
4,1920.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jacques Brugnon,4.0,False,NaN

In [80]:
bios = pd.read_csv("./data/bios.csv")

## 2.4 重新保存与格式转换

In [ ]:
#bios.to_parquet
#bio.to_csv
#bio.to_excel

# 3. Accessing Data with Pandas

## 3.1 看头部 / 尾部 / 随机数

In [12]:
coffee.head()

         Day Coffee Type  Units Sold
0     Monday    Espresso          25
1     Monday       Latte          15
2    Tuesday    Espresso          30
3    Tuesday       Latte          20
4  Wednesday    Espresso          35

In [ ]:
#看全部的数据
coffee
#其他的语法 print(coffee) 或是 display(coffee) 都可以显示全部数据,在当前的环境里也可以显示

          Day Coffee Type  Units Sold
0      Monday    Espresso          25
1      Monday       Latte          15
2     Tuesday    Espresso          30
3     Tuesday       Latte          20
4   Wednesday    Espresso          35
5   Wednesday       Latte          25
6    Thursday    Espresso          40
7    Thursday       Latte          30
8      Friday    Espresso          45
9      Friday       Latte          35
10   Saturday    Espresso          45
11   Saturday       Latte          35
12     Sunday    Espresso          45
13     Sunday       Latte          35

In [ ]:
#如果觉得数据开头结尾不是很重要并且数据量很大或是很分散，可以用sample随机抽取一些行来看看
# 括号里是采样指定的行数
coffee.sample(10)
#重复执行结果不一样，因为是随机抽取的

          Day Coffee Type  Units Sold
10   Saturday    Espresso          45
6    Thursday    Espresso          40
13     Sunday       Latte          35
8      Friday    Espresso          45
0      Monday    Espresso          25
11   Saturday       Latte          35
9      Friday       Latte          35
3     Tuesday       Latte          20
2     Tuesday    Espresso          30
5   Wednesday       Latte          25

In [ ]:
coffee.sample(10,random_state = 1)
#random_state参数可以让每次随机抽取的结果一样，参数值可以是任意整数，
# 或者是None（默认值），如果是None，每次抽取的结果都不一样
#如果是固定值，每次抽取的结果都一样
#底层逻辑是随机数种子
#可以叫做repeatable或是deterministic确定性的

          Day Coffee Type  Units Sold
3     Tuesday       Latte          20
7    Thursday       Latte          30
6    Thursday    Espresso          40
2     Tuesday    Espresso          30
10   Saturday    Espresso          45
4   Wednesday    Espresso          35
1      Monday       Latte          15
12     Sunday    Espresso          45
0      Monday    Espresso          25
13     Sunday       Latte          35

## 3.2 具体取行或者列

In [ ]:
#loc iloc
#coffee.loc[row,column]
coffee.loc[0]
#展示出来的效果是左边是列名，右边是对应的具体值，最下面有一个索引值0，还有类型

Day              Monday
Coffee Type    Espresso
Units Sold           25
Name: 0, dtype: object

In [22]:
coffee.head()

         Day Coffee Type  Units Sold
0     Monday    Espresso          25
1     Monday       Latte          15
2    Tuesday    Espresso          30
3    Tuesday       Latte          20
4  Wednesday    Espresso          35

In [21]:
coffee.loc[[0,1,2]]

       Day Coffee Type  Units Sold
0   Monday    Espresso          25
1   Monday       Latte          15
2  Tuesday    Espresso          30

In [23]:
#slice
coffee.loc[0:2]

       Day Coffee Type  Units Sold
0   Monday    Espresso          25
1   Monday       Latte          15
2  Tuesday    Espresso          30

In [24]:
#末尾没写就是默认的显示直到最后一行
coffee.loc[0:]

          Day Coffee Type  Units Sold
0      Monday    Espresso          25
1      Monday       Latte          15
2     Tuesday    Espresso          30
3     Tuesday       Latte          20
4   Wednesday    Espresso          35
5   Wednesday       Latte          25
6    Thursday    Espresso          40
7    Thursday       Latte          30
8      Friday    Espresso          45
9      Friday       Latte          35
10   Saturday    Espresso          45
11   Saturday       Latte          35
12     Sunday    Espresso          45
13     Sunday       Latte          35

In [ ]:
#开头不写默认是从第0行开始
coffee.loc[:5]

         Day Coffee Type  Units Sold
0     Monday    Espresso          25
1     Monday       Latte          15
2    Tuesday    Espresso          30
3    Tuesday       Latte          20
4  Wednesday    Espresso          35
5  Wednesday       Latte          25

In [ ]:
#特例切片，前后都包含
coffee.loc[5:8]

         Day Coffee Type  Units Sold
5  Wednesday       Latte          25
6   Thursday    Espresso          40
7   Thursday       Latte          30
8     Friday    Espresso          45

In [28]:
coffee.loc[5:8,"Day"]

5    Wednesday
6     Thursday
7     Thursday
8       Friday
Name: Day, dtype: str

In [29]:
coffee.loc[5:8,["Day","Units Sold"]]

         Day  Units Sold
5  Wednesday          25
6   Thursday          40
7   Thursday          30
8     Friday          45

In [30]:
coffee.loc[:,["Day","Units Sold"]]

          Day  Units Sold
0      Monday          25
1      Monday          15
2     Tuesday          30
3     Tuesday          20
4   Wednesday          35
5   Wednesday          25
6    Thursday          40
7    Thursday          30
8      Friday          45
9      Friday          35
10   Saturday          45
11   Saturday          35
12     Sunday          45
13     Sunday          35

In [ ]:
#iloc不能使用标签索引，而是标签对应的位置
coffee.iloc[:,[0,2]]
#.loc 的上界包含，是闭区间，.iloc 的上界不包含,是开区间

          Day  Units Sold
0      Monday          25
1      Monday          15
2     Tuesday          30
3     Tuesday          20
4   Wednesday          35
5   Wednesday          25
6    Thursday          40
7    Thursday          30
8      Friday          45
9      Friday          35
10   Saturday          45
11   Saturday          35
12     Sunday          45
13     Sunday          35

In [36]:
coffee.index = coffee["Day"]
coffee[0:4]

             Day Coffee Type  Units Sold
Day
Monday    Monday    Espresso          25
Monday    Monday       Latte          15
Tuesday  Tuesday    Espresso          30
Tuesday  Tuesday       Latte          20

In [37]:
#这个时候使用loc就会出错
coffee.loc[0:4]

TypeError: cannot do slice indexing on Index with these indexers [0] of type int

In [38]:
coffee.iloc[0:2]

           Day Coffee Type  Units Sold
Day
Monday  Monday    Espresso          25
Monday  Monday       Latte          15

In [39]:
coffee.loc["Monday"]

           Day Coffee Type  Units Sold
Day
Monday  Monday    Espresso          25
Monday  Monday       Latte          15

In [40]:
coffee.loc["Monday":"Wednesday"]

                 Day Coffee Type  Units Sold
Day
Monday        Monday    Espresso          25
Monday        Monday       Latte          15
Tuesday      Tuesday    Espresso          30
Tuesday      Tuesday       Latte          20
Wednesday  Wednesday    Espresso          35
Wednesday  Wednesday       Latte          25

In [ ]:
#到这一步就可以做一些简单的数据分析了，比如周一到周三的销量总和
coffee.loc["Monday":"Wednesday","Units Sold"]

Day
Monday       25
Monday       15
Tuesday      30
Tuesday      20
Wednesday    35
Wednesday    25
Name: Units Sold, dtype: int64

## 3.3 修改值

In [52]:
coffee

    index        Day Coffee Type  Units Sold
0       0     Monday    Espresso          25
1       1     Monday       Latte          15
2       2    Tuesday    Espresso          30
3       3    Tuesday       Latte          20
4       4  Wednesday    Espresso          35
5       5  Wednesday       Latte          25
6       6   Thursday    Espresso          40
7       7   Thursday       Latte          30
8       8     Friday    Espresso          45
9       9     Friday       Latte          35
10     10   Saturday    Espresso          45
11     11   Saturday       Latte          35
12     12     Sunday    Espresso          45
13     13     Sunday       Latte          35

In [54]:
#drop的作用：当前index列是day，如果drop为false就是不删掉的话，原本的index列会变成新的表的一列
#也就是drop决定的是旧的 index 要不要变成表里的普通一列
coffee = coffee.reset_index(drop=True)
coffee

          Day Coffee Type  Units Sold
0      Monday    Espresso          25
1      Monday       Latte          15
2     Tuesday    Espresso          30
3     Tuesday       Latte          20
4   Wednesday    Espresso          35
5   Wednesday       Latte          25
6    Thursday    Espresso          40
7    Thursday       Latte          30
8      Friday    Espresso          45
9      Friday       Latte          35
10   Saturday    Espresso          45
11   Saturday       Latte          35
12     Sunday    Espresso          45
13     Sunday       Latte          35

In [ ]:
#如果某一列数据出错，可以直接修改
#设置单个值
coffee.loc[1,"Units Sold"] = 10
coffee

          Day Coffee Type  Units Sold
0      Monday    Espresso          25
1      Monday       Latte          10
2     Tuesday    Espresso          30
3     Tuesday       Latte          20
4   Wednesday    Espresso          35
5   Wednesday       Latte          25
6    Thursday    Espresso          40
7    Thursday       Latte          30
8      Friday    Espresso          45
9      Friday       Latte          35
10   Saturday    Espresso          45
11   Saturday       Latte          35
12     Sunday    Espresso          45
13     Sunday       Latte          35

In [63]:
#设置多个值
coffee.loc[1:2,"Units Sold"] = [10,11]#或者直接等于某个值比如10
coffee.loc[1:2]

       Day Coffee Type  Units Sold
1   Monday       Latte          10
2  Tuesday    Espresso          11

In [ ]:
#at只能取一个值,行和列都不能传入多个
coffee.at[1,"Units Sold"]

np.int64(10)

In [ ]:
#类似于loc和iloc，也有at和iat
coffee.iat[1,2]

np.int64(10)

In [ ]:
#其他方法，取某一列
#但是对于Units Sold这种列名有空格的，不能用点语法
#so bracket syntax is a bit more robust that graes us a colunnh
#也就是说括号语法比点语法更健壮，因为点语法会把列名当成属性，如果列名有空格或者是一些特殊字符，点语法就不能用
coffee.Day

0        Monday
1        Monday
2       Tuesday
3       Tuesday
4     Wednesday
5     Wednesday
6      Thursday
7      Thursday
8        Friday
9        Friday
10     Saturday
11     Saturday
12       Sunday
13       Sunday
Name: Day, dtype: str

In [70]:
coffee["Day"]

0        Monday
1        Monday
2       Tuesday
3       Tuesday
4     Wednesday
5     Wednesday
6      Thursday
7      Thursday
8        Friday
9        Friday
10     Saturday
11     Saturday
12       Sunday
13       Sunday
Name: Day, dtype: str

In [ ]:
#升序increasing number
coffee.sort_values("Units Sold")

          Day Coffee Type  Units Sold
1      Monday       Latte          10
2     Tuesday    Espresso          11
3     Tuesday       Latte          20
0      Monday    Espresso          25
5   Wednesday       Latte          25
7    Thursday       Latte          30
4   Wednesday    Espresso          35
9      Friday       Latte          35
13     Sunday       Latte          35
11   Saturday       Latte          35
6    Thursday    Espresso          40
8      Friday    Espresso          45
10   Saturday    Espresso          45
12     Sunday    Espresso          45

In [72]:
#decreasing number
coffee.sort_values("Units Sold",ascending = False)

          Day Coffee Type  Units Sold
10   Saturday    Espresso          45
8      Friday    Espresso          45
12     Sunday    Espresso          45
6    Thursday    Espresso          40
4   Wednesday    Espresso          35
11   Saturday       Latte          35
13     Sunday       Latte          35
9      Friday       Latte          35
7    Thursday       Latte          30
0      Monday    Espresso          25
5   Wednesday       Latte          25
3     Tuesday       Latte          20
2     Tuesday    Espresso          11
1      Monday       Latte          10

In [ ]:
#可以使用0，1代表False，True
#可以同时指定不同index的升序或是降序
#可以传入多个index名
#当传入多个index名时，默认是按照第一个index进行排序，如果第一个index有重复值，就会按照第二个index进行排序，以此类推
#如果是字母，默认排序时aplhabetical的（字母序）
coffee.sort_values(["Units Sold","Coffee Type"],ascending = [0,1])

In [ ]:
#会损失一些表现分lose some performance但是在偶尔需要逐行查看的时候可以使用迭代器
#not align with pandas optimizated part /syntax语法
#try to use more pandas bulit-in functions
for index,row in coffee.iterrows():
    print(index)
    print(row)
    print("----")

0
Day              Monday
Coffee Type    Espresso
Units Sold           25
Name: 0, dtype: object
----
1
Day            Monday
Coffee Type     Latte
Units Sold         10
Name: 1, dtype: object
----
2
Day             Tuesday
Coffee Type    Espresso
Units Sold           11
Name: 2, dtype: object
----
3
Day            Tuesday
Coffee Type      Latte
Units Sold          20
Name: 3, dtype: object
----
4
Day            Wednesday
Coffee Type     Espresso
Units Sold            35
Name: 4, dtype: object
----
5
Day            Wednesday
Coffee Type        Latte
Units Sold            25
Name: 5, dtype: object
----
6
Day            Thursday
Coffee Type    Espresso
Units Sold           40
Name: 6, dtype: object
----
7
Day            Thursday
Coffee Type       Latte
Units Sold           30
Name: 7, dtype: object
----
8
Day              Friday
Coffee Type    Espresso
Units Sold           45
Name: 8, dtype: object
----
9
Day            Friday
Coffee Type     Latte
Units Sold         35
Name: 9, dtype: object
----
10
Day            Saturday
Coffee Type    Espresso
Units Sold           45
Name: 10, dtype: object
----
11
Day            Saturday
Coffee Type       Latte
Units Sold           35
Name: 11, dtype: object
----
12
Day              Sunday
Coffee Type    Espresso
Units Sold           45
Name: 12, dtype: object
----
13
Day            Sunday
Coffee Type     Latte
Units Sold         35
Name: 13, dtype: object
----

In [78]:
for index,row in coffee.iterrows():
    print(index)
    print(row["Units Sold"])
    print("----")

0
25
----
1
10
----
2
11
----
3
20
----
4
35
----
5
25
----
6
40
----
7
30
----
8
45
----
9
35
----
10
45
----
11
35
----
12
45
----
13
35
----

# 4. Filtering data

## 4.1 conditional request条件查询

In [81]:
bios.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25

In [82]:
bios.tail()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
145495,149222,Polina Luchnikova,2002-01-30,Serov,Sverdlovsk,RUS,ROC,167.0,61.0,NaN
145496,149223,Valeriya Merkusheva,1999-09-20,Moskva (Moscow),Moskva,RUS,ROC,168.0,65.0,NaN
145497,149224,Yuliya Smirnova,1998-05-08,Kotlas,Arkhangelsk,RUS,ROC,163.0,55.0,NaN
145498,149225,André Foussard,1899-05-19,Niort,Deux-Sèvres,FRA,France,166.0,NaN,1986-03-18
145499,149814,Bill Phillips,1913-07-15,Dulwich Hill,New South Wales,AUS,Australia,NaN,NaN,2003-10-20

In [83]:
bios.info()

<class 'pandas.DataFrame'>
RangeIndex: 145500 entries, 0 to 145499
Data columns (total 10 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   athlete_id    145500 non-null  int64
 1   name          145500 non-null  str
 2   born_date     143693 non-null  str
 3   born_city     110908 non-null  str
 4   born_region   110908 non-null  str
 5   born_country  110908 non-null  str
 6   NOC           145499 non-null  str
 7   height_cm     106651 non-null  float64
 8   weight_kg     102070 non-null  float64
 9   died_date     33940 non-null   str
dtypes: float64(2), int64(1), str(7)
memory usage: 18.5 MB

In [88]:
bios.loc[bios["height_cm"] > 215]

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
5089,5108,Viktor Pankrashkin,1957-06-19,Moskva (Moscow),Moskva,RUS,Soviet Union,220.0,112.0,1993-07-24
5583,5606,Paulinho Villas Boas,1963-01-26,São Paulo,São Paulo,BRA,Brazil,217.0,106.0,NaN
5673,5696,Gunther Behnke,1963-01-19,Leverkusen,Nordrhein-Westfalen,GER,Germany,221.0,114.0,NaN
5716,5739,Uwe Blab,1962-03-26,München (Munich),Bayern,GER,Germany West Germany,218.0,110.0,NaN
5781,5804,Tommy Burleson,1952-02-24,Crossnore,North Carolina,USA,United States,223.0,102.0,NaN
5796,5819,Andy Campbell,1956-07-21,Melbourne,Victoria,AUS,Australia,218.0,93.0,NaN
6223,6250,Lars Hansen,1954-09-27,København (Copenhagen),Hovedstaden,DEN,Canada,216.0,105.0,NaN
6270,6298,Hu Zhangbao,1963-04-05,NaN,NaN,NaN,People's Republic of China,216.0,135.0,NaN
6409,6440,Sergey Kovalenko,1947-08-11,NaN,NaN,NaN,Soviet Union,216.0,111.0,2004-11-18
6420,6451,Jānis Krūmiņš,1930-01-30,Cēsis,Cēsu novads,LAT,Soviet Union,218.0,141.0,1994-11-20
6504,6537,Luc Longley,1969-01-19,Melbourne,Victoria,AUS,Australia,220.0,135.0,NaN
6722,6755,Shaquille O'Neal,1972-03-06,Newark,New Jersey,USA,United States,216.0,137.0,NaN
6937,6972,David Robinson,1965-08-06,Key West,Florida,USA,United States,216.0,107.0,NaN
6978,7013,Arvydas Sabonis,1964-12-19,Kaunas,Kaunas,LTU,Lithuania Soviet Union,223.0,122.0,NaN
7074,7111,Paulo da Silva,1963-07-21,São Paulo,São Paulo,BRA,Brazil,217.0,106.0,NaN
7188,7226,Vladimir Tkachenko,1957-09-20,Golovinka,Krasnodar Kray,RUS,Soviet Union,220.0,110.0,NaN
7281,7320,Stojko Vranković,1964-01-22,Drniš,Šibensko-kninska županija,CRO,Croatia Yugoslavia,217.0,115.0,NaN
7376,7416,Eurelijus Žukauskas,1973-08-22,Klaipėda,Klaipėda,LTU,Lithuania,218.0,115.0,NaN
52608,52983,Aleksey Kazakov,1976-03-18,Naberezhnye Chelny,Respublika Tatarstan,RUS,Russian Federation,217.0,102.0,NaN
82100,82753,Frédéric Weis,1977-06-22,Thionville,Moselle,FRA,France,218.0,110.0,NaN
89070,89782,Yao Ming,1980-09-12,Xuhui District,Shanghai,CHN,People's Republic of China,226.0,141.0,NaN
89075,89787,Roberto Dueñas,1975-11-01,Madrid,Madrid,ESP,Spain,221.0,137.0,NaN
107408,108533,Peter John Ramos,1985-05-23,Fajardo,Puerto Rico,PUR,Puerto Rico,219.0,113.0,NaN
112312,113568,Stanko Barać,1986-08-13,Mostar,Hercegovačko-neretvanski kanton,BIH,Croatia,217.0,110.0,NaN
112332,113588,Andreas Glyniadakis,1981-08-26,Chania,Kriti,GRE,Greece,216.0,115.0,NaN
112337,113593,Hamed Haddadi,1985-05-19,Ahvaz,Khuzestan,IRI,Islamic Republic of Iran,218.0,110.0,NaN
118663,120400,Timofey Mozgov,1986-07-16,NaN,NaN,NaN,Russian Federation,216.0,113.0,NaN
118676,120415,Dmitry Musersky,1988-10-29,Makiïvka,Donetsk,UKR,Russian Federation,219.0,104.0,NaN
120266,122147,Zhang Zhaoxu,1987-11-18,Binzhou,Shandong,CHN,People's Republic of China,221.0,110.0,NaN
121694,123709,Salah Mejri,1986-06-15,Jendouba,Jendouba,TUN,Tunisia,216.0,110.0,NaN
123850,126093,Tyson Chandler,1982-10-02,Hanford,California,USA,United States,216.0,107.0,NaN
130460,133147,Li Muhao,1992-06-02,Guiyang,Guizhou,CHN,People's Republic of China,218.0,115.0,NaN
130461,133148,Zhou Qi,1996-01-16,Xinxiang,Henan,CHN,People's Republic of China,217.0,95.0,NaN
138671,142084,Ondřej Balvín,1992-09-20,Ústí nad Labem,Ústecký kraj,CZE,Czechia,216.0,107.0,NaN
139365,142836,Moustapha Fall,1992-02-23,Paris,Paris,FRA,France,218.0,NaN,NaN

In [87]:
bios.loc[bios["height_cm"] > 215,["name","height_cm"]]

                         name  height_cm
5089       Viktor Pankrashkin      220.0
5583     Paulinho Villas Boas      217.0
5673           Gunther Behnke      221.0
5716                 Uwe Blab      218.0
5781           Tommy Burleson      223.0
5796            Andy Campbell      218.0
6223              Lars Hansen      216.0
6270              Hu Zhangbao      216.0
6409         Sergey Kovalenko      216.0
6420            Jānis Krūmiņš      218.0
6504              Luc Longley      220.0
6722         Shaquille O'Neal      216.0
6937           David Robinson      216.0
6978          Arvydas Sabonis      223.0
7074           Paulo da Silva      217.0
7188       Vladimir Tkachenko      220.0
7281         Stojko Vranković      217.0
7376      Eurelijus Žukauskas      218.0
52608         Aleksey Kazakov      217.0
82100           Frédéric Weis      218.0
89070                Yao Ming      226.0
89075          Roberto Dueñas      221.0
107408       Peter John Ramos      219.0
112312           Stanko Barać      217.0
112332    Andreas Glyniadakis      216.0
112337          Hamed Haddadi      218.0
118663         Timofey Mozgov      216.0
118676        Dmitry Musersky      219.0
120266           Zhang Zhaoxu      221.0
121694            Salah Mejri      216.0
123850         Tyson Chandler      216.0
130460               Li Muhao      218.0
130461                Zhou Qi      217.0
138671          Ondřej Balvín      216.0
139365         Moustapha Fall      218.0

In [90]:
#shorthand syntax简写的语法
bios[bios["height_cm"] > 215]

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
5089,5108,Viktor Pankrashkin,1957-06-19,Moskva (Moscow),Moskva,RUS,Soviet Union,220.0,112.0,1993-07-24
5583,5606,Paulinho Villas Boas,1963-01-26,São Paulo,São Paulo,BRA,Brazil,217.0,106.0,NaN
5673,5696,Gunther Behnke,1963-01-19,Leverkusen,Nordrhein-Westfalen,GER,Germany,221.0,114.0,NaN
5716,5739,Uwe Blab,1962-03-26,München (Munich),Bayern,GER,Germany West Germany,218.0,110.0,NaN
5781,5804,Tommy Burleson,1952-02-24,Crossnore,North Carolina,USA,United States,223.0,102.0,NaN
5796,5819,Andy Campbell,1956-07-21,Melbourne,Victoria,AUS,Australia,218.0,93.0,NaN
6223,6250,Lars Hansen,1954-09-27,København (Copenhagen),Hovedstaden,DEN,Canada,216.0,105.0,NaN
6270,6298,Hu Zhangbao,1963-04-05,NaN,NaN,NaN,People's Republic of China,216.0,135.0,NaN
6409,6440,Sergey Kovalenko,1947-08-11,NaN,NaN,NaN,Soviet Union,216.0,111.0,2004-11-18
6420,6451,Jānis Krūmiņš,1930-01-30,Cēsis,Cēsu novads,LAT,Soviet Union,218.0,141.0,1994-11-20
6504,6537,Luc Longley,1969-01-19,Melbourne,Victoria,AUS,Australia,220.0,135.0,NaN
6722,6755,Shaquille O'Neal,1972-03-06,Newark,New Jersey,USA,United States,216.0,137.0,NaN
6937,6972,David Robinson,1965-08-06,Key West,Florida,USA,United States,216.0,107.0,NaN
6978,7013,Arvydas Sabonis,1964-12-19,Kaunas,Kaunas,LTU,Lithuania Soviet Union,223.0,122.0,NaN
7074,7111,Paulo da Silva,1963-07-21,São Paulo,São Paulo,BRA,Brazil,217.0,106.0,NaN
7188,7226,Vladimir Tkachenko,1957-09-20,Golovinka,Krasnodar Kray,RUS,Soviet Union,220.0,110.0,NaN
7281,7320,Stojko Vranković,1964-01-22,Drniš,Šibensko-kninska županija,CRO,Croatia Yugoslavia,217.0,115.0,NaN
7376,7416,Eurelijus Žukauskas,1973-08-22,Klaipėda,Klaipėda,LTU,Lithuania,218.0,115.0,NaN
52608,52983,Aleksey Kazakov,1976-03-18,Naberezhnye Chelny,Respublika Tatarstan,RUS,Russian Federation,217.0,102.0,NaN
82100,82753,Frédéric Weis,1977-06-22,Thionville,Moselle,FRA,France,218.0,110.0,NaN
89070,89782,Yao Ming,1980-09-12,Xuhui District,Shanghai,CHN,People's Republic of China,226.0,141.0,NaN
89075,89787,Roberto Dueñas,1975-11-01,Madrid,Madrid,ESP,Spain,221.0,137.0,NaN
107408,108533,Peter John Ramos,1985-05-23,Fajardo,Puerto Rico,PUR,Puerto Rico,219.0,113.0,NaN
112312,113568,Stanko Barać,1986-08-13,Mostar,Hercegovačko-neretvanski kanton,BIH,Croatia,217.0,110.0,NaN
112332,113588,Andreas Glyniadakis,1981-08-26,Chania,Kriti,GRE,Greece,216.0,115.0,NaN
112337,113593,Hamed Haddadi,1985-05-19,Ahvaz,Khuzestan,IRI,Islamic Republic of Iran,218.0,110.0,NaN
118663,120400,Timofey Mozgov,1986-07-16,NaN,NaN,NaN,Russian Federation,216.0,113.0,NaN
118676,120415,Dmitry Musersky,1988-10-29,Makiïvka,Donetsk,UKR,Russian Federation,219.0,104.0,NaN
120266,122147,Zhang Zhaoxu,1987-11-18,Binzhou,Shandong,CHN,People's Republic of China,221.0,110.0,NaN
121694,123709,Salah Mejri,1986-06-15,Jendouba,Jendouba,TUN,Tunisia,216.0,110.0,NaN
123850,126093,Tyson Chandler,1982-10-02,Hanford,California,USA,United States,216.0,107.0,NaN
130460,133147,Li Muhao,1992-06-02,Guiyang,Guizhou,CHN,People's Republic of China,218.0,115.0,NaN
130461,133148,Zhou Qi,1996-01-16,Xinxiang,Henan,CHN,People's Republic of China,217.0,95.0,NaN
138671,142084,Ondřej Balvín,1992-09-20,Ústí nad Labem,Ústecký kraj,CZE,Czechia,216.0,107.0,NaN
139365,142836,Moustapha Fall,1992-02-23,Paris,Paris,FRA,France,218.0,NaN,NaN

In [ ]:
#跟矩阵用法或是二维数组索引一样，但是要注意括号uu
bios[bios["height_cm"] > 215][["name","height_cm"]]

                         name  height_cm
5089       Viktor Pankrashkin      220.0
5583     Paulinho Villas Boas      217.0
5673           Gunther Behnke      221.0
5716                 Uwe Blab      218.0
5781           Tommy Burleson      223.0
5796            Andy Campbell      218.0
6223              Lars Hansen      216.0
6270              Hu Zhangbao      216.0
6409         Sergey Kovalenko      216.0
6420            Jānis Krūmiņš      218.0
6504              Luc Longley      220.0
6722         Shaquille O'Neal      216.0
6937           David Robinson      216.0
6978          Arvydas Sabonis      223.0
7074           Paulo da Silva      217.0
7188       Vladimir Tkachenko      220.0
7281         Stojko Vranković      217.0
7376      Eurelijus Žukauskas      218.0
52608         Aleksey Kazakov      217.0
82100           Frédéric Weis      218.0
89070                Yao Ming      226.0
89075          Roberto Dueñas      221.0
107408       Peter John Ramos      219.0
112312           Stanko Barać      217.0
112332    Andreas Glyniadakis      216.0
112337          Hamed Haddadi      218.0
118663         Timofey Mozgov      216.0
118676        Dmitry Musersky      219.0
120266           Zhang Zhaoxu      221.0
121694            Salah Mejri      216.0
123850         Tyson Chandler      216.0
130460               Li Muhao      218.0
130461                Zhou Qi      217.0
138671          Ondřej Balvín      216.0
139365         Moustapha Fall      218.0

In [ ]:
#注意两个表达式需要有括号
bios[(bios["height_cm"] > 215) & (bios["born_country"] == "USA")]

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
5781,5804,Tommy Burleson,1952-02-24,Crossnore,North Carolina,USA,United States,223.0,102.0,NaN
6722,6755,Shaquille O'Neal,1972-03-06,Newark,New Jersey,USA,United States,216.0,137.0,NaN
6937,6972,David Robinson,1965-08-06,Key West,Florida,USA,United States,216.0,107.0,NaN
123850,126093,Tyson Chandler,1982-10-02,Hanford,California,USA,United States,216.0,107.0,NaN

In [104]:
bios[bios["name"].str.contains("keith")]

Empty DataFrame
Columns: [athlete_id, name, born_date, born_city, born_region, born_country, NOC, height_cm, weight_kg, died_date]
Index: []

In [105]:
bios[bios["name"].str.contains("Keith")]

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
1897,1907,Keith Hanlon,1966-09-01,NaN,NaN,NaN,Ireland,NaN,NaN,NaN
3505,3517,Keith Wallace,1961-03-29,Preston,England,GBR,Great Britain,165.0,51.0,1999-12-31
6228,6255,Keith Hartley,1940-10-15,Vancouver,British Columbia,CAN,Canada,200.0,85.0,NaN
8898,8946,Keith Mwila,1966-01-01,NaN,NaN,NaN,Zambia,NaN,NaN,1993-01-09
12053,12118,Keith Hervey,1898-11-03,Fulham,England,GBR,Great Britain,NaN,NaN,1973-02-22
...,...,...,...,...,...,...,...,...,...,...
109900,111105,Keith Cumberpatch,1927-08-25,Christchurch,Canterbury,NZL,New Zealand,NaN,NaN,2013-11-15
115973,117348,Keith Sanderson,1975-02-02,Plymouth,Massachusetts,USA,United States,183.0,95.0,NaN
117676,119195,Duncan Keith,1983-07-16,Winnipeg,Manitoba,CAN,Canada,185.0,88.0,NaN
122121,124176,Keith Ferguson,1979-09-07,Sale,Victoria,AUS,Australia,176.0,78.0,NaN
127310,129749,Tracy Keith-Matchitt,1990-03-30,Palmerston North,Manawatu-Wanganui,NZL,Cook Islands,167.0,60.0,NaN

In [106]:
#case = false的意思是无视大小写，默认为true也就是大小写敏感
bios[bios["name"].str.contains("keith", case=False)]

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
1897,1907,Keith Hanlon,1966-09-01,NaN,NaN,NaN,Ireland,NaN,NaN,NaN
3505,3517,Keith Wallace,1961-03-29,Preston,England,GBR,Great Britain,165.0,51.0,1999-12-31
6228,6255,Keith Hartley,1940-10-15,Vancouver,British Columbia,CAN,Canada,200.0,85.0,NaN
8898,8946,Keith Mwila,1966-01-01,NaN,NaN,NaN,Zambia,NaN,NaN,1993-01-09
12053,12118,Keith Hervey,1898-11-03,Fulham,England,GBR,Great Britain,NaN,NaN,1973-02-22
...,...,...,...,...,...,...,...,...,...,...
109900,111105,Keith Cumberpatch,1927-08-25,Christchurch,Canterbury,NZL,New Zealand,NaN,NaN,2013-11-15
115973,117348,Keith Sanderson,1975-02-02,Plymouth,Massachusetts,USA,United States,183.0,95.0,NaN
117676,119195,Duncan Keith,1983-07-16,Winnipeg,Manitoba,CAN,Canada,185.0,88.0,NaN
122121,124176,Keith Ferguson,1979-09-07,Sale,Victoria,AUS,Australia,176.0,78.0,NaN
127310,129749,Tracy Keith-Matchitt,1990-03-30,Palmerston North,Manawatu-Wanganui,NZL,Cook Islands,167.0,60.0,NaN

In [ ]:
#引号里可以使用正则表达式regular expression
#正则表达式又回到了那些$r之类的可以表示连续或是只包含一个的强大的功能
bios[bios["name"].str.contains("keith|Patrick", case=False)]

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
6,7,Patrick Chila,1969-11-27,Ris-Orangis,Essonne,FRA,France,180.0,73.0,NaN
119,120,Patrick Wheatley,1899-01-20,Vryheid,KwaZulu-Natal,RSA,Great Britain,NaN,NaN,1967-11-05
319,320,Patrick De Koning,1961-04-23,Dendermonde,Oost-Vlaanderen,BEL,Belgium,178.0,92.0,NaN
1897,1907,Keith Hanlon,1966-09-01,NaN,NaN,NaN,Ireland,NaN,NaN,NaN
2115,2125,Patrick Jopp,1962-01-08,NaN,NaN,NaN,Switzerland,176.0,67.0,NaN
...,...,...,...,...,...,...,...,...,...,...
143975,147633,Patrick Chinyemba,2001-01-03,NaN,NaN,NaN,Zambia,NaN,NaN,NaN
144172,147850,Patrick Jakob,1996-10-17,Sankt Johann in Tirol,Tirol,AUT,Austria,NaN,NaN,NaN
144547,148239,Patrick Galbraith,1986-03-11,Haderslev,Syddanmark,DEN,Denmark,NaN,NaN,NaN
144565,148257,Patrick Russell,1993-01-04,Gentofte,Hovedstaden,DEN,Denmark,186.0,93.0,NaN
145435,149158,Patrick Gasienica,1998-11-28,McHenry,Illinois,USA,United States,NaN,NaN,2023-06-12

In [108]:
#regex = False的意思是把引号里的内容当成普通的字符串，而不是正则表达式,因此找不到完全匹配的
bios[bios["name"].str.contains("keith|Patrick", case=False,regex = False)]

Empty DataFrame
Columns: [athlete_id, name, born_date, born_city, born_region, born_country, NOC, height_cm, weight_kg, died_date]
Index: []

In [ ]:
#记得矩阵匹配是包含在括号里的，而不是单另直接写括号就行
bios[bios["born_country"].isin(["USA","UK"])]

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
54,55,Monique Javer,1967-07-22,Burlingame,California,USA,Great Britain,177.0,64.0,NaN
960,964,Xóchitl Escobedo,1968-09-17,West Covina,California,USA,Mexico,170.0,60.0,NaN
961,965,Angélica Gavaldón,1973-10-03,El Centro,California,USA,Mexico,160.0,54.0,NaN
1231,1238,Bert Schneider,1897-07-01,Cleveland,Ohio,USA,Canada,NaN,NaN,1986-02-20
1345,1352,Laura Berg,1975-01-06,Santa Fe Springs,California,USA,United States,168.0,61.0,NaN
...,...,...,...,...,...,...,...,...,...,...
145445,149168,Kristen Santos,1994-11-02,Fairfield,Connecticut,USA,United States,NaN,NaN,NaN
145446,149169,Corinne Stoddard,2001-08-15,Seattle,Washington,USA,United States,NaN,NaN,NaN
145454,149180,Anna Hoffmann,2000-03-28,Madison,Wisconsin,USA,United States,NaN,NaN,NaN
145457,149183,Alix Wilkinson,2000-08-02,Mammoth Lakes,California,USA,United States,NaN,NaN,NaN
145468,149195,Justin Abdelkader,1987-02-25,Muskegon,Michigan,USA,United States,187.0,97.0,NaN

In [ ]:
#是startswith而不是startwith
#可以在表达式里直接用&合并
bios[bios["born_country"].isin(["USA","UK"]) & bios["name"].str.startswith("Keith")]

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
50929,51288,Keith Carter,1924-08-30,Akron,Ohio,USA,United States,NaN,NaN,2013-05-03
51185,51544,Keith Russell,1948-01-15,Mesa,Arizona,USA,United States,188.0,73.0,NaN
52913,53288,Keith Erickson,1944-04-19,San Francisco,California,USA,United States,196.0,86.0,NaN
62678,63144,Keith Notary,1960-01-22,Merritt Island,Florida,USA,United States,170.0,66.0,NaN
77550,78141,Keith Brantly,1962-05-23,Scott Air Force Base,Illinois,USA,United States,180.0,64.0,NaN
84097,84766,Keith Christiansen,1944-07-14,International Falls,Minnesota,USA,United States,165.0,69.0,2018-11-05
94646,95413,Keith Meyer,1938-06-20,Geneva,Illinois,USA,United States,NaN,NaN,2010-07-25
97499,98286,Keith Tkachuk,1972-03-28,Melrose,Massachusetts,USA,United States,188.0,102.0,NaN
98068,98860,Keith Wegeman,1929-08-28,Denver,Colorado,USA,United States,NaN,NaN,1974-08-22
99921,100722,Keith Carney,1970-02-03,Providence,Rhode Island,USA,United States,188.0,93.0,NaN
115973,117348,Keith Sanderson,1975-02-02,Plymouth,Massachusetts,USA,United States,183.0,95.0,NaN

In [113]:
#另一种写法，query，记得引号里是and,还有字符串需要单引号包含双引号或是双引号包含单引号
bios.query("born_country == 'USA' and born_city == 'Seattle'")

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
11030,11088,David Halpern,1955-08-18,Seattle,Washington,USA,United States,178.0,79.0,NaN
12800,12870,Todd Trewin,1958-04-20,Seattle,Washington,USA,United States,180.0,75.0,NaN
15476,15583,Scott McKinley,1968-10-15,Seattle,Washington,USA,United States,183.0,75.0,NaN
29079,29293,Joyce Tanac,1950-09-27,Seattle,Washington,USA,United States,156.0,49.0,NaN
31135,31371,Bill Kuhlemeier,1908-01-14,Seattle,Washington,USA,United States,NaN,NaN,2001-07-08
...,...,...,...,...,...,...,...,...,...,...
133392,136331,Hans Struzyna,1989-03-31,Seattle,Washington,USA,United States,188.0,91.0,NaN
135448,138662,Maude Davis Crossland,2003-03-19,Seattle,Washington,USA,Colombia,NaN,NaN,NaN
136993,140229,Jenell Berhorst,2003-12-13,Seattle,Washington,USA,United States,NaN,NaN,NaN
143507,147159,Nevin Harrison,2002-06-02,Seattle,Washington,USA,United States,175.0,73.0,NaN
145446,149169,Corinne Stoddard,2001-08-15,Seattle,Washington,USA,United States,NaN,NaN,NaN

## 4.2 add and remove 增删

In [114]:
coffee.head()

         Day Coffee Type  Units Sold
0     Monday    Espresso          25
1     Monday       Latte          10
2    Tuesday    Espresso          11
3    Tuesday       Latte          20
4  Wednesday    Espresso          35

In [ ]:
#新增一列
coffee["Price"] = 4.99
#也可以用矩阵coffee["Price"] = [4.99,5.99,6.99,7.99,8.99]

In [116]:
coffee.head()

         Day Coffee Type  Units Sold  Price
0     Monday    Espresso          25   4.99
1     Monday       Latte          10   4.99
2    Tuesday    Espresso          11   4.99
3    Tuesday       Latte          20   4.99
4  Wednesday    Espresso          35   4.99

In [117]:
import numpy as np
#where条件语句内置/lambda
coffee["New_Price"] =np.where(coffee["Coffee Type"] == "Espresso",5.99,4.99)

In [118]:
coffee.head()

         Day Coffee Type  Units Sold  Price  New_Price
0     Monday    Espresso          25   4.99       5.99
1     Monday       Latte          10   4.99       4.99
2    Tuesday    Espresso          11   4.99       5.99
3    Tuesday       Latte          20   4.99       4.99
4  Wednesday    Espresso          35   4.99       5.99

In [119]:
coffee_copy = pd.read_csv('./warmup-data/coffee.csv')
coffee_copy.head()

         Day Coffee Type  Units Sold
0     Monday    Espresso          25
1     Monday       Latte          15
2    Tuesday    Espresso          30
3    Tuesday       Latte          20
4  Wednesday    Espresso          35

In [ ]:
coffee_try = coffee_copy
coffee_try["Price"] = 4.99
coffee_copy.head()
#这里可以看到coffee_try和coffee_copy指向的是同一个对象，而不是像其它语言一样另开一个内存

         Day Coffee Type  Units Sold  Price
0     Monday    Espresso          25   4.99
1     Monday       Latte          15   4.99
2    Tuesday    Espresso          30   4.99
3    Tuesday       Latte          20   4.99
4  Wednesday    Espresso          35   4.99

In [122]:
#可以使用.copy()方法来创造一个新的对象，来避免修改原来的对象
coffee_copy = pd.read_csv('./warmup-data/coffee.csv')
coffee_try = coffee_copy.copy()
coffee_try.head()

         Day Coffee Type  Units Sold
0     Monday    Espresso          25
1     Monday       Latte          15
2    Tuesday    Espresso          30
3    Tuesday       Latte          20
4  Wednesday    Espresso          35

In [ ]:
coffee_try["Price"] = 4.99
coffee_copy.head()
#可以看到原来的coffee_copy没有被coffee_try影响

         Day Coffee Type  Units Sold
0     Monday    Espresso          25
1     Monday       Latte          15
2    Tuesday    Espresso          30
3    Tuesday       Latte          20
4  Wednesday    Espresso          35

In [124]:
coffee.head()

         Day Coffee Type  Units Sold  Price  New_Price
0     Monday    Espresso          25   4.99       5.99
1     Monday       Latte          10   4.99       4.99
2    Tuesday    Espresso          11   4.99       5.99
3    Tuesday       Latte          20   4.99       4.99
4  Wednesday    Espresso          35   4.99       5.99

In [125]:
#删除列
coffee.drop("Price",axis = 1, inplace = True)
coffee.head()

         Day Coffee Type  Units Sold  New_Price
0     Monday    Espresso          25       5.99
1     Monday       Latte          10       4.99
2    Tuesday    Espresso          11       5.99
3    Tuesday       Latte          20       4.99
4  Wednesday    Espresso          35       5.99

In [126]:
#或者另一种方法
coffee["Price"] = 4.99
coffee.head()

         Day Coffee Type  Units Sold  New_Price  Price
0     Monday    Espresso          25       5.99   4.99
1     Monday       Latte          10       4.99   4.99
2    Tuesday    Espresso          11       5.99   4.99
3    Tuesday       Latte          20       4.99   4.99
4  Wednesday    Espresso          35       5.99   4.99

In [ ]:
#使用column = 列名来去掉列
coffee.drop(columns = "Price",inplace = True)
#默认inplace = False,这个时候可以通过赋值；或者就是直接为True，会修改原来对象
coffee.head()

         Day Coffee Type  Units Sold  New_Price
0     Monday    Espresso          25       5.99
1     Monday       Latte          10       4.99
2    Tuesday    Espresso          11       5.99
3    Tuesday       Latte          20       4.99
4  Wednesday    Espresso          35       5.99

In [128]:
coffee["Price"] = 4.99
coffee.head()

         Day Coffee Type  Units Sold  New_Price  Price
0     Monday    Espresso          25       5.99   4.99
1     Monday       Latte          10       4.99   4.99
2    Tuesday    Espresso          11       5.99   4.99
3    Tuesday       Latte          20       4.99   4.99
4  Wednesday    Espresso          35       5.99   4.99

In [129]:
coffee.drop(columns = "Price")

          Day Coffee Type  Units Sold  New_Price
0      Monday    Espresso          25       5.99
1      Monday       Latte          10       4.99
2     Tuesday    Espresso          11       5.99
3     Tuesday       Latte          20       4.99
4   Wednesday    Espresso          35       5.99
5   Wednesday       Latte          25       4.99
6    Thursday    Espresso          40       5.99
7    Thursday       Latte          30       4.99
8      Friday    Espresso          45       5.99
9      Friday       Latte          35       4.99
10   Saturday    Espresso          45       5.99
11   Saturday       Latte          35       4.99
12     Sunday    Espresso          45       5.99
13     Sunday       Latte          35       4.99

In [ ]:
coffee.head()
#可以看到原本的没有修改

         Day Coffee Type  Units Sold  New_Price  Price
0     Monday    Espresso          25       5.99   4.99
1     Monday       Latte          10       4.99   4.99
2    Tuesday    Espresso          11       5.99   4.99
3    Tuesday       Latte          20       4.99   4.99
4  Wednesday    Espresso          35       5.99   4.99

In [ ]:
#通过赋值可以看到修改了
coffee = coffee.drop(columns = "Price")
coffee.head()

         Day Coffee Type  Units Sold  New_Price
0     Monday    Espresso          25       5.99
1     Monday       Latte          10       4.99
2    Tuesday    Espresso          11       5.99
3    Tuesday       Latte          20       4.99
4  Wednesday    Espresso          35       5.99

In [133]:
#或者直接指定列名
coffee["Price"] = 4.99
coffee = coffee[["Day","Coffee Type","Units Sold","New_Price"]]
coffee.head()

         Day Coffee Type  Units Sold  New_Price
0     Monday    Espresso          25       5.99
1     Monday       Latte          10       4.99
2    Tuesday    Espresso          11       5.99
3    Tuesday       Latte          20       4.99
4  Wednesday    Espresso          35       5.99

In [134]:
#可以使用简单的加减乘除新增列
coffee["Revenue"] = coffee["Units Sold"] * coffee["New_Price"]
coffee.head()

         Day Coffee Type  Units Sold  New_Price  Revenue
0     Monday    Espresso          25       5.99   149.75
1     Monday       Latte          10       4.99    49.90
2    Tuesday    Espresso          11       5.99    65.89
3    Tuesday       Latte          20       4.99    99.80
4  Wednesday    Espresso          35       5.99   209.65

In [ ]:
#rename重命名列
#这里也保持了相同的就是要么默认inplace = False,通过赋值来修改；或者就是直接为True，会修改原来对象
coffee.rename(columns = {"New_Price":"Price"},inplace = True)

In [136]:
coffee.head()

         Day Coffee Type  Units Sold  Price  Revenue
0     Monday    Espresso          25   5.99   149.75
1     Monday       Latte          10   4.99    49.90
2    Tuesday    Espresso          11   5.99    65.89
3    Tuesday       Latte          20   4.99    99.80
4  Wednesday    Espresso          35   5.99   209.65

In [137]:
#更细的列名拆分
bios.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25

In [138]:
bios_new = bios.copy()

In [139]:
#空格拆分之后取了第一个
bios_new["first_name"] = bios_new["name"].str.split().str[0]

In [140]:
bios_new.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,first_name
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,Jean-François
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN,Arnaud
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17,Jean
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20,Jacques
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25,Albert

In [143]:
#年份的处理可以转换成另一种日期格式
bios_new["born_datatime"] = pd.to_datetime(bios_new["born_date"])
bios_new.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,first_name,born_datatime
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,Jean-François,1886-12-12
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN,Arnaud,1969-04-01
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17,Jean,1898-08-13
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20,Jacques,1895-05-11
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25,Albert,1878-04-17

In [ ]:
bios_new.info()
#可以看到变成另一种格式的，原本是str

<class 'pandas.DataFrame'>
RangeIndex: 145500 entries, 0 to 145499
Data columns (total 12 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   athlete_id     145500 non-null  int64
 1   name           145500 non-null  str
 2   born_date      143693 non-null  str
 3   born_city      110908 non-null  str
 4   born_region    110908 non-null  str
 5   born_country   110908 non-null  str
 6   NOC            145499 non-null  str
 7   height_cm      106651 non-null  float64
 8   weight_kg      102070 non-null  float64
 9   died_date      33940 non-null   str
 10  first_name     145500 non-null  object
 11  born_datatime  143693 non-null  datetime64[us]
dtypes: datetime64[us](1), float64(2), int64(1), object(1), str(7)
memory usage: 20.7+ MB

In [150]:
bios_new["born_year"] = bios_new["born_datatime"].dt.year
bios_new[["first_name","born_year"]].head()

      first_name  born_year
0  Jean-François     1886.0
1         Arnaud     1969.0
2           Jean     1898.0
3        Jacques     1895.0
4         Albert     1878.0

In [ ]:
#可以根据新的列做筛选
bios_new[bios_new["first_name"] == "Keith"]

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,first_name,born_datatime,born_year
1897,1907,Keith Hanlon,1966-09-01,NaN,NaN,NaN,Ireland,NaN,NaN,NaN,Keith,1966-09-01,1966.0
3505,3517,Keith Wallace,1961-03-29,Preston,England,GBR,Great Britain,165.0,51.0,1999-12-31,Keith,1961-03-29,1961.0
6228,6255,Keith Hartley,1940-10-15,Vancouver,British Columbia,CAN,Canada,200.0,85.0,NaN,Keith,1940-10-15,1940.0
8898,8946,Keith Mwila,1966-01-01,NaN,NaN,NaN,Zambia,NaN,NaN,1993-01-09,Keith,1966-01-01,1966.0
12053,12118,Keith Hervey,1898-11-03,Fulham,England,GBR,Great Britain,NaN,NaN,1973-02-22,Keith,1898-11-03,1898.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
99921,100722,Keith Carney,1970-02-03,Providence,Rhode Island,USA,United States,188.0,93.0,NaN,Keith,1970-02-03,1970.0
102227,103168,Keith Beavers,1983-02-09,London,Ontario,CAN,Canada,185.0,75.0,NaN,Keith,1983-02-09,1983.0
109900,111105,Keith Cumberpatch,1927-08-25,Christchurch,Canterbury,NZL,New Zealand,NaN,NaN,2013-11-15,Keith,1927-08-25,1927.0
115973,117348,Keith Sanderson,1975-02-02,Plymouth,Massachusetts,USA,United States,183.0,95.0,NaN,Keith,1975-02-02,1975.0
122121,124176,Keith Ferguson,1979-09-07,Sale,Victoria,AUS,Australia,176.0,78.0,NaN,Keith,1979-09-07,1979.0

In [ ]:
#参数errors='coerce'：无法解析的无效日期会自动转为 NaT（时间类型空值），不会整行报错中断程序
#bios_new['born_datetime'] = pd.to_datetime(bios_new['born_date'], errors='coerce')

In [ ]:
#参数format指定日期的格式输入，%Y代表四位数的年份，%m代表两位数的月份，%d代表两位数的日期
bios_new["born_datatime2"] = pd.to_datetime(bios_new["born_date"], format = "%Y-%m-%d")
bios_new.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,first_name,born_datatime,born_year,born_datatime2
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,Jean-François,1886-12-12,1886.0,1886-12-12
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN,Arnaud,1969-04-01,1969.0,1969-04-01
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17,Jean,1898-08-13,1898.0,1898-08-13
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20,Jacques,1895-05-11,1895.0,1895-05-11
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25,Albert,1878-04-17,1878.0,1878-04-17